// Generated by gencpp from file mavros/CommandBool.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_COMMANDBOOL_H
#define MAVROS_MESSAGE_COMMANDBOOL_H

#include <ros/service_traits.h>


#include <mavros/CommandBoolRequest.h>
#include <mavros/CommandBoolResponse.h>


namespace mavros
{

struct CommandBool
{

typedef CommandBoolRequest Request;
typedef CommandBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandBool
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::CommandBool > {
  static const char* value()
  {
    return "e09abbb4e5bae6b558e5010966eb6e9e";
  }

  static const char* value(const ::mavros::CommandBool&) { return value(); }
};

template<>
struct DataType< ::mavros::CommandBool > {
  static const char* value()
  {
    return "mavros/CommandBool";
  }

  static const char* value(const ::mavros::CommandBool&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::CommandBoolRequest> should match 
// service_traits::MD5Sum< ::mavros::CommandBool > 
template<>
struct MD5Sum< ::mavros::CommandBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::CommandBool >::value();
  }
  static const char* value(const ::mavros::CommandBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::CommandBoolRequest> should match 
// service_traits::DataType< ::mavros::CommandBool > 
template<>
struct DataType< ::mavros::CommandBoolRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::CommandBool >::value();
  }
  static const char* value(const ::mavros::CommandBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::CommandBoolResponse> should match 
// service_traits::MD5Sum< ::mavros::CommandBool > 
template<>
struct MD5Sum< ::mavros::CommandBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::CommandBool >::value();
  }
  static const char* value(const ::mavros::CommandBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::CommandBoolResponse> should match 
// service_traits::DataType< ::mavros::CommandBool > 
template<>
struct DataType< ::mavros::CommandBoolResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::CommandBool >::value();
  }
  static const char* value(const ::mavros::CommandBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_COMMANDBOOL_H
