// Generated by gencpp from file mavros/CommandInt.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_COMMANDINT_H
#define MAVROS_MESSAGE_COMMANDINT_H

#include <ros/service_traits.h>


#include <mavros/CommandIntRequest.h>
#include <mavros/CommandIntResponse.h>


namespace mavros
{

struct CommandInt
{

typedef CommandIntRequest Request;
typedef CommandIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandInt
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::CommandInt > {
  static const char* value()
  {
    return "9f6d60288b6b3cc5234bd92e8f1287ce";
  }

  static const char* value(const ::mavros::CommandInt&) { return value(); }
};

template<>
struct DataType< ::mavros::CommandInt > {
  static const char* value()
  {
    return "mavros/CommandInt";
  }

  static const char* value(const ::mavros::CommandInt&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::CommandIntRequest> should match 
// service_traits::MD5Sum< ::mavros::CommandInt > 
template<>
struct MD5Sum< ::mavros::CommandIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::CommandInt >::value();
  }
  static const char* value(const ::mavros::CommandIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::CommandIntRequest> should match 
// service_traits::DataType< ::mavros::CommandInt > 
template<>
struct DataType< ::mavros::CommandIntRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::CommandInt >::value();
  }
  static const char* value(const ::mavros::CommandIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::CommandIntResponse> should match 
// service_traits::MD5Sum< ::mavros::CommandInt > 
template<>
struct MD5Sum< ::mavros::CommandIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::CommandInt >::value();
  }
  static const char* value(const ::mavros::CommandIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::CommandIntResponse> should match 
// service_traits::DataType< ::mavros::CommandInt > 
template<>
struct DataType< ::mavros::CommandIntResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::CommandInt >::value();
  }
  static const char* value(const ::mavros::CommandIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_COMMANDINT_H
