// Generated by gencpp from file mavros/CommandLong.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_COMMANDLONG_H
#define MAVROS_MESSAGE_COMMANDLONG_H

#include <ros/service_traits.h>


#include <mavros/CommandLongRequest.h>
#include <mavros/CommandLongResponse.h>


namespace mavros
{

struct CommandLong
{

typedef CommandLongRequest Request;
typedef CommandLongResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandLong
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::CommandLong > {
  static const char* value()
  {
    return "61a4b6ac245fda8075fde260e82de332";
  }

  static const char* value(const ::mavros::CommandLong&) { return value(); }
};

template<>
struct DataType< ::mavros::CommandLong > {
  static const char* value()
  {
    return "mavros/CommandLong";
  }

  static const char* value(const ::mavros::CommandLong&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::CommandLongRequest> should match 
// service_traits::MD5Sum< ::mavros::CommandLong > 
template<>
struct MD5Sum< ::mavros::CommandLongRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::CommandLong >::value();
  }
  static const char* value(const ::mavros::CommandLongRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::CommandLongRequest> should match 
// service_traits::DataType< ::mavros::CommandLong > 
template<>
struct DataType< ::mavros::CommandLongRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::CommandLong >::value();
  }
  static const char* value(const ::mavros::CommandLongRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::CommandLongResponse> should match 
// service_traits::MD5Sum< ::mavros::CommandLong > 
template<>
struct MD5Sum< ::mavros::CommandLongResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::CommandLong >::value();
  }
  static const char* value(const ::mavros::CommandLongResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::CommandLongResponse> should match 
// service_traits::DataType< ::mavros::CommandLong > 
template<>
struct DataType< ::mavros::CommandLongResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::CommandLong >::value();
  }
  static const char* value(const ::mavros::CommandLongResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_COMMANDLONG_H
