// Generated by gencpp from file mavros/CommandHome.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_COMMANDHOME_H
#define MAVROS_MESSAGE_COMMANDHOME_H

#include <ros/service_traits.h>


#include <mavros/CommandHomeRequest.h>
#include <mavros/CommandHomeResponse.h>


namespace mavros
{

struct CommandHome
{

typedef CommandHomeRequest Request;
typedef CommandHomeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandHome
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::CommandHome > {
  static const char* value()
  {
    return "3e89d38ecf947c9e62eb2e14dfa6e65d";
  }

  static const char* value(const ::mavros::CommandHome&) { return value(); }
};

template<>
struct DataType< ::mavros::CommandHome > {
  static const char* value()
  {
    return "mavros/CommandHome";
  }

  static const char* value(const ::mavros::CommandHome&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::CommandHomeRequest> should match 
// service_traits::MD5Sum< ::mavros::CommandHome > 
template<>
struct MD5Sum< ::mavros::CommandHomeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::CommandHome >::value();
  }
  static const char* value(const ::mavros::CommandHomeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::CommandHomeRequest> should match 
// service_traits::DataType< ::mavros::CommandHome > 
template<>
struct DataType< ::mavros::CommandHomeRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::CommandHome >::value();
  }
  static const char* value(const ::mavros::CommandHomeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::CommandHomeResponse> should match 
// service_traits::MD5Sum< ::mavros::CommandHome > 
template<>
struct MD5Sum< ::mavros::CommandHomeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::CommandHome >::value();
  }
  static const char* value(const ::mavros::CommandHomeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::CommandHomeResponse> should match 
// service_traits::DataType< ::mavros::CommandHome > 
template<>
struct DataType< ::mavros::CommandHomeResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::CommandHome >::value();
  }
  static const char* value(const ::mavros::CommandHomeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_COMMANDHOME_H
