// Generated by gencpp from file mavros/FileRemove.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_FILEREMOVE_H
#define MAVROS_MESSAGE_FILEREMOVE_H

#include <ros/service_traits.h>


#include <mavros/FileRemoveRequest.h>
#include <mavros/FileRemoveResponse.h>


namespace mavros
{

struct FileRemove
{

typedef FileRemoveRequest Request;
typedef FileRemoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FileRemove
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::FileRemove > {
  static const char* value()
  {
    return "1c309002d7f7c6df7d3f094925ea8e10";
  }

  static const char* value(const ::mavros::FileRemove&) { return value(); }
};

template<>
struct DataType< ::mavros::FileRemove > {
  static const char* value()
  {
    return "mavros/FileRemove";
  }

  static const char* value(const ::mavros::FileRemove&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::FileRemoveRequest> should match 
// service_traits::MD5Sum< ::mavros::FileRemove > 
template<>
struct MD5Sum< ::mavros::FileRemoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::FileRemove >::value();
  }
  static const char* value(const ::mavros::FileRemoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::FileRemoveRequest> should match 
// service_traits::DataType< ::mavros::FileRemove > 
template<>
struct DataType< ::mavros::FileRemoveRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::FileRemove >::value();
  }
  static const char* value(const ::mavros::FileRemoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::FileRemoveResponse> should match 
// service_traits::MD5Sum< ::mavros::FileRemove > 
template<>
struct MD5Sum< ::mavros::FileRemoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::FileRemove >::value();
  }
  static const char* value(const ::mavros::FileRemoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::FileRemoveResponse> should match 
// service_traits::DataType< ::mavros::FileRemove > 
template<>
struct DataType< ::mavros::FileRemoveResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::FileRemove >::value();
  }
  static const char* value(const ::mavros::FileRemoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_FILEREMOVE_H
