// Generated by gencpp from file mavros/FileTruncate.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_FILETRUNCATE_H
#define MAVROS_MESSAGE_FILETRUNCATE_H

#include <ros/service_traits.h>


#include <mavros/FileTruncateRequest.h>
#include <mavros/FileTruncateResponse.h>


namespace mavros
{

struct FileTruncate
{

typedef FileTruncateRequest Request;
typedef FileTruncateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FileTruncate
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::FileTruncate > {
  static const char* value()
  {
    return "71bf45fe3600fc220a82346ce1d1430c";
  }

  static const char* value(const ::mavros::FileTruncate&) { return value(); }
};

template<>
struct DataType< ::mavros::FileTruncate > {
  static const char* value()
  {
    return "mavros/FileTruncate";
  }

  static const char* value(const ::mavros::FileTruncate&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::FileTruncateRequest> should match 
// service_traits::MD5Sum< ::mavros::FileTruncate > 
template<>
struct MD5Sum< ::mavros::FileTruncateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::FileTruncate >::value();
  }
  static const char* value(const ::mavros::FileTruncateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::FileTruncateRequest> should match 
// service_traits::DataType< ::mavros::FileTruncate > 
template<>
struct DataType< ::mavros::FileTruncateRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::FileTruncate >::value();
  }
  static const char* value(const ::mavros::FileTruncateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::FileTruncateResponse> should match 
// service_traits::MD5Sum< ::mavros::FileTruncate > 
template<>
struct MD5Sum< ::mavros::FileTruncateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::FileTruncate >::value();
  }
  static const char* value(const ::mavros::FileTruncateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::FileTruncateResponse> should match 
// service_traits::DataType< ::mavros::FileTruncate > 
template<>
struct DataType< ::mavros::FileTruncateResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::FileTruncate >::value();
  }
  static const char* value(const ::mavros::FileTruncateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_FILETRUNCATE_H
