// Generated by gencpp from file mavros/FileList.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_FILELIST_H
#define MAVROS_MESSAGE_FILELIST_H

#include <ros/service_traits.h>


#include <mavros/FileListRequest.h>
#include <mavros/FileListResponse.h>


namespace mavros
{

struct FileList
{

typedef FileListRequest Request;
typedef FileListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FileList
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::FileList > {
  static const char* value()
  {
    return "1647c627907cac72fa2d06e0e5f96aac";
  }

  static const char* value(const ::mavros::FileList&) { return value(); }
};

template<>
struct DataType< ::mavros::FileList > {
  static const char* value()
  {
    return "mavros/FileList";
  }

  static const char* value(const ::mavros::FileList&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::FileListRequest> should match 
// service_traits::MD5Sum< ::mavros::FileList > 
template<>
struct MD5Sum< ::mavros::FileListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::FileList >::value();
  }
  static const char* value(const ::mavros::FileListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::FileListRequest> should match 
// service_traits::DataType< ::mavros::FileList > 
template<>
struct DataType< ::mavros::FileListRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::FileList >::value();
  }
  static const char* value(const ::mavros::FileListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::FileListResponse> should match 
// service_traits::MD5Sum< ::mavros::FileList > 
template<>
struct MD5Sum< ::mavros::FileListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::FileList >::value();
  }
  static const char* value(const ::mavros::FileListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::FileListResponse> should match 
// service_traits::DataType< ::mavros::FileList > 
template<>
struct DataType< ::mavros::FileListResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::FileList >::value();
  }
  static const char* value(const ::mavros::FileListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_FILELIST_H
