// Generated by gencpp from file mavros/FileRename.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_FILERENAME_H
#define MAVROS_MESSAGE_FILERENAME_H

#include <ros/service_traits.h>


#include <mavros/FileRenameRequest.h>
#include <mavros/FileRenameResponse.h>


namespace mavros
{

struct FileRename
{

typedef FileRenameRequest Request;
typedef FileRenameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FileRename
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::FileRename > {
  static const char* value()
  {
    return "07d853e3d48c88a648998515aab1f5b7";
  }

  static const char* value(const ::mavros::FileRename&) { return value(); }
};

template<>
struct DataType< ::mavros::FileRename > {
  static const char* value()
  {
    return "mavros/FileRename";
  }

  static const char* value(const ::mavros::FileRename&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::FileRenameRequest> should match 
// service_traits::MD5Sum< ::mavros::FileRename > 
template<>
struct MD5Sum< ::mavros::FileRenameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::FileRename >::value();
  }
  static const char* value(const ::mavros::FileRenameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::FileRenameRequest> should match 
// service_traits::DataType< ::mavros::FileRename > 
template<>
struct DataType< ::mavros::FileRenameRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::FileRename >::value();
  }
  static const char* value(const ::mavros::FileRenameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::FileRenameResponse> should match 
// service_traits::MD5Sum< ::mavros::FileRename > 
template<>
struct MD5Sum< ::mavros::FileRenameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::FileRename >::value();
  }
  static const char* value(const ::mavros::FileRenameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::FileRenameResponse> should match 
// service_traits::DataType< ::mavros::FileRename > 
template<>
struct DataType< ::mavros::FileRenameResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::FileRename >::value();
  }
  static const char* value(const ::mavros::FileRenameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_FILERENAME_H
