// Generated by gencpp from file mavros/FileRead.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_FILEREAD_H
#define MAVROS_MESSAGE_FILEREAD_H

#include <ros/service_traits.h>


#include <mavros/FileReadRequest.h>
#include <mavros/FileReadResponse.h>


namespace mavros
{

struct FileRead
{

typedef FileReadRequest Request;
typedef FileReadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FileRead
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::FileRead > {
  static const char* value()
  {
    return "7700526a6a54d8971e0db6dc1d712523";
  }

  static const char* value(const ::mavros::FileRead&) { return value(); }
};

template<>
struct DataType< ::mavros::FileRead > {
  static const char* value()
  {
    return "mavros/FileRead";
  }

  static const char* value(const ::mavros::FileRead&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::FileReadRequest> should match 
// service_traits::MD5Sum< ::mavros::FileRead > 
template<>
struct MD5Sum< ::mavros::FileReadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::FileRead >::value();
  }
  static const char* value(const ::mavros::FileReadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::FileReadRequest> should match 
// service_traits::DataType< ::mavros::FileRead > 
template<>
struct DataType< ::mavros::FileReadRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::FileRead >::value();
  }
  static const char* value(const ::mavros::FileReadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::FileReadResponse> should match 
// service_traits::MD5Sum< ::mavros::FileRead > 
template<>
struct MD5Sum< ::mavros::FileReadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::FileRead >::value();
  }
  static const char* value(const ::mavros::FileReadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::FileReadResponse> should match 
// service_traits::DataType< ::mavros::FileRead > 
template<>
struct DataType< ::mavros::FileReadResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::FileRead >::value();
  }
  static const char* value(const ::mavros::FileReadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_FILEREAD_H
