// Generated by gencpp from file mavros/FileMakeDir.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_FILEMAKEDIR_H
#define MAVROS_MESSAGE_FILEMAKEDIR_H

#include <ros/service_traits.h>


#include <mavros/FileMakeDirRequest.h>
#include <mavros/FileMakeDirResponse.h>


namespace mavros
{

struct FileMakeDir
{

typedef FileMakeDirRequest Request;
typedef FileMakeDirResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FileMakeDir
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::FileMakeDir > {
  static const char* value()
  {
    return "f140c5ef05b00c3cfc30d5a2061b4d63";
  }

  static const char* value(const ::mavros::FileMakeDir&) { return value(); }
};

template<>
struct DataType< ::mavros::FileMakeDir > {
  static const char* value()
  {
    return "mavros/FileMakeDir";
  }

  static const char* value(const ::mavros::FileMakeDir&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::FileMakeDirRequest> should match 
// service_traits::MD5Sum< ::mavros::FileMakeDir > 
template<>
struct MD5Sum< ::mavros::FileMakeDirRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::FileMakeDir >::value();
  }
  static const char* value(const ::mavros::FileMakeDirRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::FileMakeDirRequest> should match 
// service_traits::DataType< ::mavros::FileMakeDir > 
template<>
struct DataType< ::mavros::FileMakeDirRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::FileMakeDir >::value();
  }
  static const char* value(const ::mavros::FileMakeDirRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::FileMakeDirResponse> should match 
// service_traits::MD5Sum< ::mavros::FileMakeDir > 
template<>
struct MD5Sum< ::mavros::FileMakeDirResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::FileMakeDir >::value();
  }
  static const char* value(const ::mavros::FileMakeDirResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::FileMakeDirResponse> should match 
// service_traits::DataType< ::mavros::FileMakeDir > 
template<>
struct DataType< ::mavros::FileMakeDirResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::FileMakeDir >::value();
  }
  static const char* value(const ::mavros::FileMakeDirResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_FILEMAKEDIR_H
