// Generated by gencpp from file mavros/ParamPush.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_PARAMPUSH_H
#define MAVROS_MESSAGE_PARAMPUSH_H

#include <ros/service_traits.h>


#include <mavros/ParamPushRequest.h>
#include <mavros/ParamPushResponse.h>


namespace mavros
{

struct ParamPush
{

typedef ParamPushRequest Request;
typedef ParamPushResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamPush
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::ParamPush > {
  static const char* value()
  {
    return "d3fc4d8cefa193382985a92a041a2a3d";
  }

  static const char* value(const ::mavros::ParamPush&) { return value(); }
};

template<>
struct DataType< ::mavros::ParamPush > {
  static const char* value()
  {
    return "mavros/ParamPush";
  }

  static const char* value(const ::mavros::ParamPush&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::ParamPushRequest> should match 
// service_traits::MD5Sum< ::mavros::ParamPush > 
template<>
struct MD5Sum< ::mavros::ParamPushRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::ParamPush >::value();
  }
  static const char* value(const ::mavros::ParamPushRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::ParamPushRequest> should match 
// service_traits::DataType< ::mavros::ParamPush > 
template<>
struct DataType< ::mavros::ParamPushRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::ParamPush >::value();
  }
  static const char* value(const ::mavros::ParamPushRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::ParamPushResponse> should match 
// service_traits::MD5Sum< ::mavros::ParamPush > 
template<>
struct MD5Sum< ::mavros::ParamPushResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::ParamPush >::value();
  }
  static const char* value(const ::mavros::ParamPushResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::ParamPushResponse> should match 
// service_traits::DataType< ::mavros::ParamPush > 
template<>
struct DataType< ::mavros::ParamPushResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::ParamPush >::value();
  }
  static const char* value(const ::mavros::ParamPushResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_PARAMPUSH_H
