// Generated by gencpp from file mavros/ParamSet.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_PARAMSET_H
#define MAVROS_MESSAGE_PARAMSET_H

#include <ros/service_traits.h>


#include <mavros/ParamSetRequest.h>
#include <mavros/ParamSetResponse.h>


namespace mavros
{

struct ParamSet
{

typedef ParamSetRequest Request;
typedef ParamSetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParamSet
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::ParamSet > {
  static const char* value()
  {
    return "67c3e64c93166b2201499faec7aea3ed";
  }

  static const char* value(const ::mavros::ParamSet&) { return value(); }
};

template<>
struct DataType< ::mavros::ParamSet > {
  static const char* value()
  {
    return "mavros/ParamSet";
  }

  static const char* value(const ::mavros::ParamSet&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::ParamSetRequest> should match 
// service_traits::MD5Sum< ::mavros::ParamSet > 
template<>
struct MD5Sum< ::mavros::ParamSetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::ParamSet >::value();
  }
  static const char* value(const ::mavros::ParamSetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::ParamSetRequest> should match 
// service_traits::DataType< ::mavros::ParamSet > 
template<>
struct DataType< ::mavros::ParamSetRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::ParamSet >::value();
  }
  static const char* value(const ::mavros::ParamSetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::ParamSetResponse> should match 
// service_traits::MD5Sum< ::mavros::ParamSet > 
template<>
struct MD5Sum< ::mavros::ParamSetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::ParamSet >::value();
  }
  static const char* value(const ::mavros::ParamSetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::ParamSetResponse> should match 
// service_traits::DataType< ::mavros::ParamSet > 
template<>
struct DataType< ::mavros::ParamSetResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::ParamSet >::value();
  }
  static const char* value(const ::mavros::ParamSetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_PARAMSET_H
