// Generated by gencpp from file mavros/SetMode.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_SETMODE_H
#define MAVROS_MESSAGE_SETMODE_H

#include <ros/service_traits.h>


#include <mavros/SetModeRequest.h>
#include <mavros/SetModeResponse.h>


namespace mavros
{

struct SetMode
{

typedef SetModeRequest Request;
typedef SetModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMode
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::SetMode > {
  static const char* value()
  {
    return "48ecf639e39052f8856a839dcddf826a";
  }

  static const char* value(const ::mavros::SetMode&) { return value(); }
};

template<>
struct DataType< ::mavros::SetMode > {
  static const char* value()
  {
    return "mavros/SetMode";
  }

  static const char* value(const ::mavros::SetMode&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::SetModeRequest> should match 
// service_traits::MD5Sum< ::mavros::SetMode > 
template<>
struct MD5Sum< ::mavros::SetModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::SetMode >::value();
  }
  static const char* value(const ::mavros::SetModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::SetModeRequest> should match 
// service_traits::DataType< ::mavros::SetMode > 
template<>
struct DataType< ::mavros::SetModeRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::SetMode >::value();
  }
  static const char* value(const ::mavros::SetModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::SetModeResponse> should match 
// service_traits::MD5Sum< ::mavros::SetMode > 
template<>
struct MD5Sum< ::mavros::SetModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::SetMode >::value();
  }
  static const char* value(const ::mavros::SetModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::SetModeResponse> should match 
// service_traits::DataType< ::mavros::SetMode > 
template<>
struct DataType< ::mavros::SetModeResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::SetMode >::value();
  }
  static const char* value(const ::mavros::SetModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_SETMODE_H
