// Generated by gencpp from file mavros/WaypointClear.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_WAYPOINTCLEAR_H
#define MAVROS_MESSAGE_WAYPOINTCLEAR_H

#include <ros/service_traits.h>


#include <mavros/WaypointClearRequest.h>
#include <mavros/WaypointClearResponse.h>


namespace mavros
{

struct WaypointClear
{

typedef WaypointClearRequest Request;
typedef WaypointClearResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WaypointClear
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::WaypointClear > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::mavros::WaypointClear&) { return value(); }
};

template<>
struct DataType< ::mavros::WaypointClear > {
  static const char* value()
  {
    return "mavros/WaypointClear";
  }

  static const char* value(const ::mavros::WaypointClear&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::WaypointClearRequest> should match 
// service_traits::MD5Sum< ::mavros::WaypointClear > 
template<>
struct MD5Sum< ::mavros::WaypointClearRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::WaypointClear >::value();
  }
  static const char* value(const ::mavros::WaypointClearRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::WaypointClearRequest> should match 
// service_traits::DataType< ::mavros::WaypointClear > 
template<>
struct DataType< ::mavros::WaypointClearRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::WaypointClear >::value();
  }
  static const char* value(const ::mavros::WaypointClearRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::WaypointClearResponse> should match 
// service_traits::MD5Sum< ::mavros::WaypointClear > 
template<>
struct MD5Sum< ::mavros::WaypointClearResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::WaypointClear >::value();
  }
  static const char* value(const ::mavros::WaypointClearResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::WaypointClearResponse> should match 
// service_traits::DataType< ::mavros::WaypointClear > 
template<>
struct DataType< ::mavros::WaypointClearResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::WaypointClear >::value();
  }
  static const char* value(const ::mavros::WaypointClearResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_WAYPOINTCLEAR_H
