// Generated by gencpp from file mavros/WaypointSetCurrent.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_WAYPOINTSETCURRENT_H
#define MAVROS_MESSAGE_WAYPOINTSETCURRENT_H

#include <ros/service_traits.h>


#include <mavros/WaypointSetCurrentRequest.h>
#include <mavros/WaypointSetCurrentResponse.h>


namespace mavros
{

struct WaypointSetCurrent
{

typedef WaypointSetCurrentRequest Request;
typedef WaypointSetCurrentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WaypointSetCurrent
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::WaypointSetCurrent > {
  static const char* value()
  {
    return "f99aa1a911a80ab546ea470f4e90c807";
  }

  static const char* value(const ::mavros::WaypointSetCurrent&) { return value(); }
};

template<>
struct DataType< ::mavros::WaypointSetCurrent > {
  static const char* value()
  {
    return "mavros/WaypointSetCurrent";
  }

  static const char* value(const ::mavros::WaypointSetCurrent&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::WaypointSetCurrentRequest> should match 
// service_traits::MD5Sum< ::mavros::WaypointSetCurrent > 
template<>
struct MD5Sum< ::mavros::WaypointSetCurrentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::WaypointSetCurrent >::value();
  }
  static const char* value(const ::mavros::WaypointSetCurrentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::WaypointSetCurrentRequest> should match 
// service_traits::DataType< ::mavros::WaypointSetCurrent > 
template<>
struct DataType< ::mavros::WaypointSetCurrentRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::WaypointSetCurrent >::value();
  }
  static const char* value(const ::mavros::WaypointSetCurrentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::WaypointSetCurrentResponse> should match 
// service_traits::MD5Sum< ::mavros::WaypointSetCurrent > 
template<>
struct MD5Sum< ::mavros::WaypointSetCurrentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::WaypointSetCurrent >::value();
  }
  static const char* value(const ::mavros::WaypointSetCurrentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::WaypointSetCurrentResponse> should match 
// service_traits::DataType< ::mavros::WaypointSetCurrent > 
template<>
struct DataType< ::mavros::WaypointSetCurrentResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::WaypointSetCurrent >::value();
  }
  static const char* value(const ::mavros::WaypointSetCurrentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_WAYPOINTSETCURRENT_H
