// Generated by gencpp from file mavros/WaypointGOTO.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_WAYPOINTGOTO_H
#define MAVROS_MESSAGE_WAYPOINTGOTO_H

#include <ros/service_traits.h>


#include <mavros/WaypointGOTORequest.h>
#include <mavros/WaypointGOTOResponse.h>


namespace mavros
{

struct WaypointGOTO
{

typedef WaypointGOTORequest Request;
typedef WaypointGOTOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WaypointGOTO
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::WaypointGOTO > {
  static const char* value()
  {
    return "c52932a48a9836c9e3888b9ed4669183";
  }

  static const char* value(const ::mavros::WaypointGOTO&) { return value(); }
};

template<>
struct DataType< ::mavros::WaypointGOTO > {
  static const char* value()
  {
    return "mavros/WaypointGOTO";
  }

  static const char* value(const ::mavros::WaypointGOTO&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::WaypointGOTORequest> should match 
// service_traits::MD5Sum< ::mavros::WaypointGOTO > 
template<>
struct MD5Sum< ::mavros::WaypointGOTORequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::WaypointGOTO >::value();
  }
  static const char* value(const ::mavros::WaypointGOTORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::WaypointGOTORequest> should match 
// service_traits::DataType< ::mavros::WaypointGOTO > 
template<>
struct DataType< ::mavros::WaypointGOTORequest>
{
  static const char* value()
  {
    return DataType< ::mavros::WaypointGOTO >::value();
  }
  static const char* value(const ::mavros::WaypointGOTORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::WaypointGOTOResponse> should match 
// service_traits::MD5Sum< ::mavros::WaypointGOTO > 
template<>
struct MD5Sum< ::mavros::WaypointGOTOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::WaypointGOTO >::value();
  }
  static const char* value(const ::mavros::WaypointGOTOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::WaypointGOTOResponse> should match 
// service_traits::DataType< ::mavros::WaypointGOTO > 
template<>
struct DataType< ::mavros::WaypointGOTOResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::WaypointGOTO >::value();
  }
  static const char* value(const ::mavros::WaypointGOTOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_WAYPOINTGOTO_H
