// Generated by gencpp from file mavros/WaypointPull.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_WAYPOINTPULL_H
#define MAVROS_MESSAGE_WAYPOINTPULL_H

#include <ros/service_traits.h>


#include <mavros/WaypointPullRequest.h>
#include <mavros/WaypointPullResponse.h>


namespace mavros
{

struct WaypointPull
{

typedef WaypointPullRequest Request;
typedef WaypointPullResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WaypointPull
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::WaypointPull > {
  static const char* value()
  {
    return "a8d9ecef8fb37028d2db2a9aa4ed7e79";
  }

  static const char* value(const ::mavros::WaypointPull&) { return value(); }
};

template<>
struct DataType< ::mavros::WaypointPull > {
  static const char* value()
  {
    return "mavros/WaypointPull";
  }

  static const char* value(const ::mavros::WaypointPull&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::WaypointPullRequest> should match 
// service_traits::MD5Sum< ::mavros::WaypointPull > 
template<>
struct MD5Sum< ::mavros::WaypointPullRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::WaypointPull >::value();
  }
  static const char* value(const ::mavros::WaypointPullRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::WaypointPullRequest> should match 
// service_traits::DataType< ::mavros::WaypointPull > 
template<>
struct DataType< ::mavros::WaypointPullRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::WaypointPull >::value();
  }
  static const char* value(const ::mavros::WaypointPullRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::WaypointPullResponse> should match 
// service_traits::MD5Sum< ::mavros::WaypointPull > 
template<>
struct MD5Sum< ::mavros::WaypointPullResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::WaypointPull >::value();
  }
  static const char* value(const ::mavros::WaypointPullResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::WaypointPullResponse> should match 
// service_traits::DataType< ::mavros::WaypointPull > 
template<>
struct DataType< ::mavros::WaypointPullResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::WaypointPull >::value();
  }
  static const char* value(const ::mavros::WaypointPullResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_WAYPOINTPULL_H
