// Generated by gencpp from file mavros/WaypointPullResponse.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_WAYPOINTPULLRESPONSE_H
#define MAVROS_MESSAGE_WAYPOINTPULLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mavros
{
template <class ContainerAllocator>
struct WaypointPullResponse_
{
  typedef WaypointPullResponse_<ContainerAllocator> Type;

  WaypointPullResponse_()
    : success(false)
    , wp_received(0)  {
    }
  WaypointPullResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , wp_received(0)  {
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint32_t _wp_received_type;
  _wp_received_type wp_received;




  typedef boost::shared_ptr< ::mavros::WaypointPullResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros::WaypointPullResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointPullResponse_

typedef ::mavros::WaypointPullResponse_<std::allocator<void> > WaypointPullResponse;

typedef boost::shared_ptr< ::mavros::WaypointPullResponse > WaypointPullResponsePtr;
typedef boost::shared_ptr< ::mavros::WaypointPullResponse const> WaypointPullResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros::WaypointPullResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros::WaypointPullResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mavros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mavros': ['/home/deanzaka/Github/trui-bot-prj/controller/src/mavros/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'diagnostic_msgs': ['/opt/ros/indigo/share/diagnostic_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mavros::WaypointPullResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros::WaypointPullResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros::WaypointPullResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros::WaypointPullResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros::WaypointPullResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros::WaypointPullResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros::WaypointPullResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8d9ecef8fb37028d2db2a9aa4ed7e79";
  }

  static const char* value(const ::mavros::WaypointPullResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8d9ecef8fb37028ULL;
  static const uint64_t static_value2 = 0xd2db2a9aa4ed7e79ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros::WaypointPullResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros/WaypointPullResponse";
  }

  static const char* value(const ::mavros::WaypointPullResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros::WaypointPullResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
uint32 wp_received\n\
\n\
";
  }

  static const char* value(const ::mavros::WaypointPullResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros::WaypointPullResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.wp_received);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct WaypointPullResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros::WaypointPullResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros::WaypointPullResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "wp_received: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.wp_received);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MESSAGE_WAYPOINTPULLRESPONSE_H
